version: "3"
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - FILE_POSTS=/data/posts.csv
      - CHUNKSIZE=400
      - POSTS_QUEUE=client_posts_queue
    networks:
      - rabbitmq

networks:
  rabbitmq: 
    external: 
      name: reddit_memes_analyzer_rabbitmq

