version: "3"
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - FILE_POSTS=/data/posts.csv
      - CHUNKSIZE=400
      - POSTS_QUEUE=client_posts_queue
      - COMMENTS_QUEUE=client_comments_queue
      - FILE_COMMENTS=/data/comments.csv
      - RESPONSE_QUEUE=client_response_queue
      - STATUS_CHECK_QUEUE=client_status_check_queue
      - STATUS_RESPONSE_QUEUE=client_status_response_queue
      - CLIENT_ID=2
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external:
      name: rabbitmq

