version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq

  receiver:
    container_name: receiver
    image: receiver:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - COMMETS_QUEUE=comments_queue
      - POSTS_QUEUE=posts_queue
      - SEND_WORKERS_COMMENTS=2
      - SEND_WORKERS_POSTS=3
      - RECV_POSTS_QUEUE=client_posts_queue
      - RECV_COMMENTS_QUEUE=client_comments_queue
      - SEND_RESPONSE_QUEUE=client_response_queue
      - STUDENTS_QUEUE=student_url_queue
      - AVG_QUEUE=posts_avg_score_queue
      - IMAGE_QUEUE=post_avg_sentiments_queue
      - STATUS_CHECK_QUEUE=client_status_check_queue
      - STATUS_RESPONSE_QUEUE=client_status_response_queue
      - RECV_WORKERS_STUDENTS=1
      - CONTAINER_NAME=receiver
    networks:
      - rabbitmq


  comments_filter_columns_1:
    container_name: comments_filter_columns_1
    image: comments_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_queue
      - QUEUE_SEND=comments_filter_queue
      - CONTAINER_NAME=comments_filter_columns_1
    networks:
      - rabbitmq

  comments_filter_columns_2:
    container_name: comments_filter_columns_2
    image: comments_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_queue
      - QUEUE_SEND=comments_filter_queue
      - CONTAINER_NAME=comments_filter_columns_2
    networks:
      - rabbitmq


  comments_filter_student_1:
    container_name: comments_filter_student_1
    image: comments_filter_student:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=cmt_pst_join_st_queue
      - QUEUE_SEND=posts_student_queue
      - RECV_WORKERS=1
      - CONTAINER_NAME=comments_filter_student_1
    networks:
      - rabbitmq


  posts_filter_score_gte_avg_1:
    container_name: posts_filter_score_gte_avg_1
    image: posts_filter_score_gte_avg:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV_AVG=posts_avg_score_queue
      - QUEUE_RECV_STUDENTS=posts_student_queue
      - QUEUE_SEND=student_url_queue
      - CHUNKSIZE=500
      - CONTAINER_NAME=posts_filter_score_gte_avg_1
    networks:
      - rabbitmq


  posts_reduce_avg_sentiment_1:
    container_name: posts_reduce_avg_sentiment_1
    image: posts_reduce_avg_sentiment:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=cmt_pst_join_se_queue
      - QUEUE_SEND=post_sentiments_queue
      - CONTAINER_NAME=posts_reduce_avg_sentiment_1
    networks:
      - rabbitmq


  posts_max_avg_sentiment:
    container_name: posts_max_avg_sentiment
    image: posts_max_avg_sentiment:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./posts_max_avg_sentiment/data:/data
    environment:
      - QUEUE_RECV=post_sentiments_queue
      - QUEUE_SEND=post_avg_sentiments_queue
      - RECV_WORKERS=1
      - CONTAINER_NAME=posts_max_avg_sentiment
    networks:
      - rabbitmq


  posts_filter_columns_1:
    container_name: posts_filter_columns_1
    image: posts_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_queue
      - QUEUE_SEND_JOIN=posts_for_join_queue
      - QUEUE_SEND_AVG=posts_for_avg_queue
      - CONTAINER_NAME=posts_filter_columns_1
    networks:
      - rabbitmq

  posts_filter_columns_2:
    container_name: posts_filter_columns_2
    image: posts_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_queue
      - QUEUE_SEND_JOIN=posts_for_join_queue
      - QUEUE_SEND_AVG=posts_for_avg_queue
      - CONTAINER_NAME=posts_filter_columns_2
    networks:
      - rabbitmq

  posts_filter_columns_3:
    container_name: posts_filter_columns_3
    image: posts_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_queue
      - QUEUE_SEND_JOIN=posts_for_join_queue
      - QUEUE_SEND_AVG=posts_for_avg_queue
      - CONTAINER_NAME=posts_filter_columns_3
    networks:
      - rabbitmq


  posts_avg_score:
    container_name: posts_avg_score
    image: posts_avg_score:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_for_avg_queue
      - QUEUE_SEND=posts_avg_score_queue
      - RECV_WORKERS=3
      - CONTAINER_NAME=posts_avg_score
    networks:
      - rabbitmq

  join_comments_with_posts:
    container_name: join_comments_with_posts
    image: join_comments_with_posts:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - QUEUE_RECV_COMMENTS=comments_filter_queue
      - QUEUE_RECV_POSTS=posts_for_join_queue
      - QUEUE_SEND_STUDENTS=cmt_pst_join_st_queue
      - QUEUE_SEND_SENTIMENTS=cmt_pst_join_se_queue
      - CHUNKSIZE=500
      - RECV_WORKERS_COMMENTS=2
      - RECV_WORKERS_POSTS=3
      - SEND_WORKERS=1
      - CONTAINER_NAME=join_comments_with_posts
    networks:
      - rabbitmq


  healthchecker:
    image: health_check:latest
    deploy:
      replicas: 4
    environment:
      - REPLICAS=4
      - ELECTION_TIMEOUT=4
      - HEARTBEAT_SLEEP=1
      - HEARTBEAT_TIMEOUT=4
      - SLEEP_SECONDS=1
      - HEALTHCHECK_READ_TIMEOUT=2
      - HEALTHCHECK_NODE_TIMEOUT=6
      - HEALTHBEAT_DELAY=2
      - VICTORY_TIMEOUT=2
    depends_on:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./persistence/:/tmp/persistence/
    networks:
      - rabbitmq


networks:
  rabbitmq:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
