version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq

  receiver:
    container_name: receiver
    image: receiver:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - COMMETS_QUEUE=comments_queue 
      - POSTS_QUEUE=posts_queue
      - SEND_WORKERS_COMMENTS=1
      - SEND_WORKERS_POSTS=1
      - RECV_POSTS_QUEUE=client_posts_queue
      - RECV_COMMENTS_QUEUE=client_comments_queue
    networks:
      - rabbitmq

  
  comments_filter_columns_1:
    container_name: comments_filter_columns_1
    image: comments_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_queue
      - QUEUE_SEND=comments_filter_queue
    networks:
      - rabbitmq

  
  comments_filter_student_1:
    container_name: comments_filter_student_1
    image: comments_filter_student:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=cmt_pst_join_st_queue
      - QUEUE_SEND=posts_student_queue
      - RECV_WORKERS=1

  
  posts_filter_score_gte_avg_1:
    container_name: posts_filter_score_gte_avg_1
    image: posts_filter_score_gte_avg:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV_AVG=posts_avg_score_queue
      - QUEUE_RECV_STUDENTS=posts_student_queue
      - QUEUE_SEND=student_url_queue
      - CHUNKSIZE=400

  
  posts_reduce_avg_sentiment_1:
    container_name: posts_reduce_avg_sentiment_1
    image: posts_reduce_avg_sentiment:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=cmt_pst_join_se_queue
      - QUEUE_SEND=post_sentiments_queue


  posts_max_avg_sentiment:
    container_name: posts_max_avg_sentiment
    image: posts_max_avg_sentiment:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=post_sentiments_queue
      - QUEUE_SEND=post_avg_sentiments_queue
      - RECV_WORKERS=1

  
  posts_filter_columns_1:
    container_name: posts_filter_columns_1
    image: posts_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_queue
      - QUEUE_SEND_JOIN=posts_for_join_queue
      - QUEUE_SEND_AVG=posts_for_avg_queue

  posts_avg_score:
    container_name: posts_avg_score
    image: posts_avg_score:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_for_avg_queue
      - QUEUE_SEND=posts_avg_score_queue
      - RECV_WORKERS=1

  join_comments_with_posts:
    container_name: join_comments_with_posts
    image: join_comments_with_posts:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    networks: 
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV_COMMENTS=comments_filter_queue
      - QUEUE_RECV_POSTS=posts_for_join_queue
      - QUEUE_SEND_STUDENTS=cmt_pst_join_st_queue
      - QUEUE_SEND_SENTIMENTS=cmt_pst_join_se_queue
      - CHUNKSIZE=400
      - RECV_WORKERS_COMMENTS=1
      - RECV_WORKERS_POSTS=1
      - SEND_WORKERS=1



networks:
  rabbitmq:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24