version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672

  timer:
    build:
      context: src
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - REPLICAS=2
    depends_on:
      - rabbit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
